url: http://www.svacidrain.com/
baseurl: 

# Site settings
title: SV Acid Rain
email: svacidrain@gmail.com
description: "Welcome to the website of SV Acid Rain! Ride the waves, live your dream!"


# Team names, titles and social links
people:
- name: Alex
  pic: 1
  position: Captain
  bio: An experienced skipper having accumulated several thousand nautical miles including a circumnavigation of Britain, Rathlin, and the west coast of Ireland. He has sailed around the channel Islands and set out from Falmouth in 2019 to the infamous Bay of Biscay and navigate the stunning Ria's of Northern Spain then down the wild Portuguese coast and onto the Algarve. A navigation of the Guadiana river as far North as Alcutim and as far east as Gibraltar before heading south once more for the warm and windy canary Islands. Alex has also gained experience on other sailing vessels, having crossed the Bay of Biscay four times and crewed on deliveries around the UK and Europe. He also gained valuable experience as a racing crew on yachts out of Falmouth, taking part in many regattas and round-the-cans races for the Royal Cornwall yacht club. He has also crewed on more classic boats such as the working boats and gaff riggers. A born adventurer his turbulent and colourful life has seen him rub shoulders with all walks of life from ambassadors and millionaires to the homeless and orphaned. He has spent the majority of his life away from his homeland in such places as remote as north-East China and a four-year stint in Russia's vast Siberia and that is to name only a few of his adventures. This time has given him a unique character ability to integrate into many different cultures and an acceptance and understanding of people and their needs. One of his favourite sayings "I would never judge or try to understand the depths of anyone unless I had walked a lifetime in their shoes" he believes in acceptance and the brotherhood of man. 
  social:
    - title: instagram
      url: https://www.instagram.com/sv.acid.rain/

- name: Patches
  pic: 2
  position: First mate
  bio: Patches is the newest crew member on SV Acid Rain, having joined in October 2021, quickly climbing the ranks from competent crew to first mate.  
  social:
    - title: instagram
      url: https://www.instagram.com/sv.acid.rain/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/sv.acid.rain/

# Postal address (add as many lines as necessary)
address:
  - line: Around the World

# Build settings
markdown: kramdown
permalink: pretty